name: MyHomes
version: '${plugin_version}'
main: me.navoei.myhomes.MyHomes
description: A home plugin with UUID support. Allows players to invite others to their homes, as well as setting it to be public or private.
authors: [ "Navoei" ]
website: ""
api-version: '${bukkit_api_version}'